### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by imanaijan** [alekseiiagnenkov/Prog3_1#1]
1. **header-файл**
1)Хорошим тоном написания программ (в частности: сигнатур функций, имён переменных и классов, и тд) является соблюдение единообразного стиля. Названия пространств имён следует записывать в нижнем регистре.
Например, https://habr.com/ru/post/172091/
https://github.com/alekseiiagnenkov/Prog3_1/blob/1b79f139fc3eff73c1124736eaec9b903a3ea8ac/Prog3_1/Set.h#L2
2)Членам класса с модификатором private следует присваивать суффикс-подчёркивание. 
https://github.com/alekseiiagnenkov/Prog3_1/blob/1b79f139fc3eff73c1124736eaec9b903a3ea8ac/Prog3_1/Set.h#L5-L8
3)В реализации части A избыточно присутствие копирующего конструктора и деструктора. 
https://github.com/alekseiiagnenkov/Prog3_1/blob/1b79f139fc3eff73c1124736eaec9b903a3ea8ac/Prog3_1/Set.h#L13-L14
4)Названия методов и функций должны быть глаголами, быть записанными в смешанном регистре и начинаться с нижнего. Без нижнего подчеркивания.
https://github.com/alekseiiagnenkov/Prog3_1/blob/1b79f139fc3eff73c1124736eaec9b903a3ea8ac/Prog3_1/Set.h#L36-L41

2. **cpp-файл класса**
1)Орфография (message).
https://github.com/alekseiiagnenkov/Prog3_1/blob/1b79f139fc3eff73c1124736eaec9b903a3ea8ac/Prog3_1/Set.cpp#L151
https://github.com/alekseiiagnenkov/Prog3_1/blob/1b79f139fc3eff73c1124736eaec9b903a3ea8ac/Prog3_1/Set.cpp#L185

**Comment by alekseiiagnenkov** [comment]
Все ошибки были исправлены, кроме 3), конструктор копирования и деструктор оставил для понимания процессов лабораторной.
